package main

import (
	"context"
	"iter"
	"math/big"
	"time"

	"github.com/Layr-Labs/eigensdk-go/chainio/txmgr"
	cstaskmanager "github.com/Layr-Labs/eigensdk-go/examples/incredible-squaring/bindings/taskManager"
	"github.com/Layr-Labs/eigensdk-go/logging"
	taskmanager "github.com/Layr-Labs/eigensdk-go/task-manager"
	taskspammer "github.com/Layr-Labs/eigensdk-go/task-spammer"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	// 1. Create the logger where all the loggs will appear
	logger, err := logging.NewZapLogger(logging.Production)
	if err != nil {
		return
	}

	// 2. Create the ethereum client that will send the RPC messages to the node
	ethHttpClient, err := ethclient.Dial("http://localhost:8545")
	if err != nil {
		logger.Errorf("Failed to dial ethclient: %w", err)
		return
	}

	// 3. Create the transaction manager, that will manage the transaction sending

	// This pk should be related to the address passed to TaskManager as task_spammer_addr when initialized
	ecdsaPrivateKey, err := crypto.HexToECDSA("2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6")
	if err != nil {
		return
	}

	txMgr, err := txmgr.NewSimpleTxManagerFromPrivateKey(logger, ethHttpClient, ecdsaPrivateKey)
	if err != nil {
		return
	}

	// 4. Get the ABI of the task manager contract's binding
	abi, err := cstaskmanager.ContractIncredibleSquaringTaskManagerMetaData.GetAbi()
	if err != nil {
		return
	}

	// 5. Create the task creator, which will create tasks and send them to the on-chain TaskManager contract.
	// Here we use an SDK implementation that satisfies the TaskCreator interface, but you can create your own
	// wrapper which implements the interface and provide it to the Indexing Task Processor.
	// Note that in this step we define the input and output types that we are using on our AVS. In this case
	// the input and output are both big int numbers.
	taskManagerAddress := common.HexToAddress("0x2bdcc0de6be1f7d2ee689a0342d76f52e8efaba3")
	taskCreator, err := taskmanager.NewTaskManagerFromAbi[*big.Int, *big.Int](taskManagerAddress, abi, txMgr, ethHttpClient)
	if err != nil {
		return
	}

	// 6. Create the config passed to the task spammer.
	taskSpammerConfig := taskspammer.Config{
		Logger: logger,

		// This means TaskGenerator will send tasks every 10 seconds
		TimeBetweenTasks: 10 * time.Second,

		QuorumThresholdPercentage: 100,
		QuorumNumbers:             []uint8{0},
	}

	// 7. Build the task spammer, providing the task creator and the task spammer config.
	taskSpammer, err := taskspammer.NewTaskSpammer(taskCreator, taskSpammerConfig)
	if err != nil {
		return
	}

	// 8. Create the sequence that will create the input values on the tasks generated by the task spammer.
	// In this case the sequence will generate numbers in a ascending sequence growing on 1 per iteration.
	squaringSequence := NewNumberToSquareSequence()

	// 9. Run the created task spammer, passing the created sequence as parameter
	err = taskSpammer.Start(context.Background(), squaringSequence)
	if err != nil {
		return
	}
}

// Returns an iterator for the sequence 1, 2, 3, ...
func NewNumberToSquareSequence() iter.Seq[*big.Int] {
	acc := big.NewInt(1)
	delta := big.NewInt(1)
	return func(yield func(*big.Int) bool) {
		for {
			if !yield(acc) {
				break
			}
			acc.Add(acc, delta)
		}
	}
}
