package main

import (
	"context"
	"iter"
	"math/big"

	"github.com/Layr-Labs/eigensdk-go/chainio/txmgr"
	examplecommon "github.com/Layr-Labs/eigensdk-go/examples/incredible-squaring/common"
	cstaskmanager "github.com/Layr-Labs/eigensdk-go/examples/incredible-squaring/contracts/bindings/IncredibleSquaringTaskManager"
	"github.com/Layr-Labs/eigensdk-go/logging"
	taskmanager "github.com/Layr-Labs/eigensdk-go/task-manager"
	taskspammer "github.com/Layr-Labs/eigensdk-go/task-spammer"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
)

type Config struct {
	TaskManagerAddress string `toml:"task_manager_address"`

	EthHttpUrl string `toml:"eth_http_url"`

	taskspammer.Config
}

func main() {
	// 0. Create the logger where all the logs will appear
	logger, err := logging.NewZapLogger(logging.Production)
	if err != nil {
		return
	}

	// 1. Provide a struct that implements the `TaskManager` interface

	tsConfig := &Config{}
	err = examplecommon.ReadTomlConfig("config/config.toml", tsConfig)
	if err != nil {
		logger.Fatalf(err.Error())
	}

	// i. Create the ethereum client that will send the RPC messages to the node
	ethHttpClient, err := ethclient.Dial(tsConfig.EthHttpUrl)
	if err != nil {
		logger.Errorf("Failed to dial ethclient: %w", err)
		return
	}

	// ii. Create the transaction manager, that will manage the transaction sending

	// This pk should be related to the address passed to TaskManager as task_spammer_addr when initialized
	ecdsaPrivateKey, err := crypto.HexToECDSA("2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6")
	if err != nil {
		return
	}

	txMgr, err := txmgr.NewSimpleTxManagerFromPrivateKey(logger, ethHttpClient, ecdsaPrivateKey)
	if err != nil {
		return
	}

	// iii. Get the ABI of the task manager contract's binding
	abi, err := cstaskmanager.ContractIncredibleSquaringTaskManagerMetaData.GetAbi()
	if err != nil {
		return
	}

	// iv. Create the task creator, here we use our standard implementation, that can be found
	// in task-manager/task_manager_wrapper.go
	// Note that in this step we define the input and output types that we are using on our AVS. In this case
	// the input and output are both big int numbers.
	taskManagerAddress := common.HexToAddress(tsConfig.TaskManagerAddress)
	taskCreator, err := taskmanager.NewTaskManagerFromAbi[*big.Int, *big.Int](taskManagerAddress, abi, txMgr, ethHttpClient)
	if err != nil {
		logger.Errorf("Failed to create Task Creator: %w", err)
		return
	}

	// 2. Create the config passed to the task spammer.
	taskSpammerConfig := tsConfig.Config

	// 3. Create the sequence that will create the input values on the tasks generated by the task spammer.
	// In this case the sequence will generate numbers in an ascending sequence growing on 1 per iteration.
	squaringSequence := NewNumberToSquareSequence()

	// 4. Build the task spammer, providing the task creator and the task spammer config.
	taskSpammer, err := taskspammer.NewTaskSpammer(logger, taskSpammerConfig, taskCreator, squaringSequence)
	if err != nil {
		return
	}

	// 5. Run the created task spammer, passing the created sequence as parameter
	err = <-taskSpammer.Start(context.Background())
	if err != nil {
		return
	}
}

// Returns an iterator for the sequence 1, 2, 3, ...
func NewNumberToSquareSequence() iter.Seq[*big.Int] {
	acc := big.NewInt(1)
	delta := big.NewInt(1)
	return func(yield func(*big.Int) bool) {
		for {
			if !yield(acc) {
				break
			}
			acc.Add(acc, delta)
		}
	}
}
