// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigensdk-go/services/bls/operatorpubkeys (interfaces: OperatorPubkeysService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/operatorpubkeys.go -package=mocks github.com/Layr-Labs/eigensdk-go/services/bls/operatorpubkeys OperatorPubkeysService
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Layr-Labs/eigensdk-go/types"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockOperatorPubkeysService is a mock of OperatorPubkeysService interface.
type MockOperatorPubkeysService struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorPubkeysServiceMockRecorder
}

// MockOperatorPubkeysServiceMockRecorder is the mock recorder for MockOperatorPubkeysService.
type MockOperatorPubkeysServiceMockRecorder struct {
	mock *MockOperatorPubkeysService
}

// NewMockOperatorPubkeysService creates a new mock instance.
func NewMockOperatorPubkeysService(ctrl *gomock.Controller) *MockOperatorPubkeysService {
	mock := &MockOperatorPubkeysService{ctrl: ctrl}
	mock.recorder = &MockOperatorPubkeysServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperatorPubkeysService) EXPECT() *MockOperatorPubkeysServiceMockRecorder {
	return m.recorder
}

// GetOperatorPubkeys mocks base method.
func (m *MockOperatorPubkeysService) GetOperatorPubkeys(arg0 context.Context, arg1 common.Address) (types.OperatorPubkeys, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorPubkeys", arg0, arg1)
	ret0, _ := ret[0].(types.OperatorPubkeys)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetOperatorPubkeys indicates an expected call of GetOperatorPubkeys.
func (mr *MockOperatorPubkeysServiceMockRecorder) GetOperatorPubkeys(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorPubkeys", reflect.TypeOf((*MockOperatorPubkeysService)(nil).GetOperatorPubkeys), arg0, arg1)
}
