// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigensdk-go/services/ecdsa/aggregation (interfaces: EcdsaAggregationService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/aggregation.go -package=mocks github.com/Layr-Labs/eigensdk-go/services/ecdsa/aggregation EcdsaAggregationService
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	aggregation "github.com/Layr-Labs/eigensdk-go/services/ecdsa/aggregation"
	types "github.com/Layr-Labs/eigensdk-go/types"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockEcdsaAggregationService is a mock of EcdsaAggregationService interface.
type MockEcdsaAggregationService struct {
	ctrl     *gomock.Controller
	recorder *MockEcdsaAggregationServiceMockRecorder
}

// MockEcdsaAggregationServiceMockRecorder is the mock recorder for MockEcdsaAggregationService.
type MockEcdsaAggregationServiceMockRecorder struct {
	mock *MockEcdsaAggregationService
}

// NewMockEcdsaAggregationService creates a new mock instance.
func NewMockEcdsaAggregationService(ctrl *gomock.Controller) *MockEcdsaAggregationService {
	mock := &MockEcdsaAggregationService{ctrl: ctrl}
	mock.recorder = &MockEcdsaAggregationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcdsaAggregationService) EXPECT() *MockEcdsaAggregationServiceMockRecorder {
	return m.recorder
}

// GetResponseChannel mocks base method.
func (m *MockEcdsaAggregationService) GetResponseChannel() <-chan aggregation.EcdsaAggregationServiceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseChannel")
	ret0, _ := ret[0].(<-chan aggregation.EcdsaAggregationServiceResponse)
	return ret0
}

// GetResponseChannel indicates an expected call of GetResponseChannel.
func (mr *MockEcdsaAggregationServiceMockRecorder) GetResponseChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseChannel", reflect.TypeOf((*MockEcdsaAggregationService)(nil).GetResponseChannel))
}

// InitializeNewTask mocks base method.
func (m *MockEcdsaAggregationService) InitializeNewTask(arg0, arg1 uint32, arg2 []byte, arg3 []uint32, arg4 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeNewTask", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeNewTask indicates an expected call of InitializeNewTask.
func (mr *MockEcdsaAggregationServiceMockRecorder) InitializeNewTask(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeNewTask", reflect.TypeOf((*MockEcdsaAggregationService)(nil).InitializeNewTask), arg0, arg1, arg2, arg3, arg4)
}

// ProcessNewSignature mocks base method.
func (m *MockEcdsaAggregationService) ProcessNewSignature(arg0 context.Context, arg1 uint32, arg2 types.TaskResponseDigest, arg3 []byte, arg4 common.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNewSignature", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNewSignature indicates an expected call of ProcessNewSignature.
func (mr *MockEcdsaAggregationServiceMockRecorder) ProcessNewSignature(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNewSignature", reflect.TypeOf((*MockEcdsaAggregationService)(nil).ProcessNewSignature), arg0, arg1, arg2, arg3, arg4)
}
