package main

import (
	"context"
	"iter"
	"math/big"
	"time"

	"github.com/Layr-Labs/eigensdk-go/chainio/txmgr"
	"github.com/Layr-Labs/eigensdk-go/logging"
	taskmanager "github.com/Layr-Labs/eigensdk-go/task-manager"
	taskspammer "github.com/Layr-Labs/eigensdk-go/task-spammer"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"

	examplecommon "github.com/Layr-Labs/eigensdk-go/examples/incredible-dot-product/common"
	idptaskmanager "github.com/Layr-Labs/eigensdk-go/examples/incredible-dot-product/contracts/bindings/IncredibleDotProductTaskManager"
)

func main() {
	// 0. Create the logger where all the logs will appear
	logger, err := logging.NewZapLogger(logging.Production)
	if err != nil {
		println("Failure creating logger")
		return
	}

	// 1. Provide a struct that implements the `TaskManager` interface

	// i. Create the ethereum client that will send the RPC messages to the node
	ethClient, err := ethclient.Dial("http://localhost:8545")
	if err != nil {
		logger.Errorf("Failed to dial ethclient: %w", err)
		return
	}

	// ii. Create the transaction manager, that will manage the transaction sending

	// This pk should be related to the address passed to TaskManager as task_spammer_addr when initialized
	ecdsaPrivateKey, err := crypto.HexToECDSA("4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356")
	if err != nil {
		logger.Errorf("Failed to create ecdsa private key: %w", err)
		return
	}

	txMgr, err := txmgr.NewSimpleTxManagerFromPrivateKey(logger, ethClient, ecdsaPrivateKey)
	if err != nil {
		logger.Errorf("Failed to create tx manager from private key: %w", err)
		return
	}

	// iii. Get the ABI of the task manager contract's binding
	taskManagerAbi, err := idptaskmanager.ContractIncredibleDotProductTaskManagerMetaData.GetAbi()
	if err != nil {
		logger.Errorf("Failed to get task manager abi: %w", err)
		return
	}

	// iv. Create the task creator, here we use our standard implementation, that can be found
	// in task-manager/task_manager_wrapper.go
	// Note that in this step we define the input and output types that we are using on our AVS. In this case
	// the DotProductInput struct (a pair of vectors) and a big int.
	taskManagerAddr := common.HexToAddress("0x7bc06c482dead17c0e297afbc32f6e63d3846650")
	taskCreator, err := taskmanager.NewTaskManagerFromAbi[examplecommon.DotProductInput, *big.Int](taskManagerAddr, taskManagerAbi, txMgr, ethClient)
	if err != nil {
		logger.Errorf("Failed to create Task Creator: %w", err)
		return
	}

	// 2. Create the config passed to the task spammer.
	taskSpammerConfig := taskspammer.Config{
		Logger: logger,

		// This means TaskGenerator will send tasks every 10 seconds
		TimeBetweenTasks: 10 * time.Second,

		QuorumThresholdPercentage: 100,
		QuorumNumbers:             []uint8{0},
	}

	// 3. Build the task spammer, providing the task creator and the task spammer config.
	taskSpammer, err := taskspammer.NewTaskSpammer(taskCreator, taskSpammerConfig)
	if err != nil {
		logger.Errorf("Failed to create Task Spammer: %w", err)
		return
	}

	// 8. Create the sequence that will create the input values on the tasks generated by the task spammer.
	// In this case the sequence will generate a fixed key-pair defined from the iteration number in an ascending
	// sequence growing on 1 per iteration.
	linearSeq := LinearRangeSequence()

	// 5. Run the created task spammer, passing the created sequence as parameter
	err = taskSpammer.Start(context.Background(), linearSeq)
	if err != nil {
		logger.Errorf("Failure while running Task Spammer: %w", err)
		return
	}
}

// Returns an iterator for the sequence 1, 2, 3, ...
// Inspired on the one from examples/incredible-squaring/task-spammer/task_spammer_use_example.go
// Returns [[1, 2, ..., n] [1, 2, ..., n]]
func LinearRangeSequence() iter.Seq[examplecommon.DotProductInput] {
	n := big.NewInt(1)
	return func(yield func(examplecommon.DotProductInput) bool) {
		for {
			length := int(n.Int64())
			x := make([]*big.Int, length)
			y := make([]*big.Int, length)
			for i := 0; i < length; i++ {
				v := big.NewInt(int64(i + 1))
				x[i] = v
				y[i] = v
			}
			if !yield(examplecommon.DotProductInput{X: x, Y: y}) {
				break
			}
			n.Add(n, big.NewInt(1))
		}
	}
}
