// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigensdk-go/chainio/clients/avsregistry (interfaces: Subscriber)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/avsRegistryContractsSubscriber.go -package=mocks -mock_names=Subscriber=MockAVSSubscriber github.com/Layr-Labs/eigensdk-go/chainio/clients/avsregistry Subscriber
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	contractBLSApkRegistry "github.com/Layr-Labs/eigensdk-go/contracts/bindings/BLSApkRegistry"
	contractRegistryCoordinator "github.com/Layr-Labs/eigensdk-go/contracts/bindings/RegistryCoordinator"
	event "github.com/ethereum/go-ethereum/event"
	gomock "go.uber.org/mock/gomock"
)

// MockAVSSubscriber is a mock of Subscriber interface.
type MockAVSSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockAVSSubscriberMockRecorder
}

// MockAVSSubscriberMockRecorder is the mock recorder for MockAVSSubscriber.
type MockAVSSubscriberMockRecorder struct {
	mock *MockAVSSubscriber
}

// NewMockAVSSubscriber creates a new mock instance.
func NewMockAVSSubscriber(ctrl *gomock.Controller) *MockAVSSubscriber {
	mock := &MockAVSSubscriber{ctrl: ctrl}
	mock.recorder = &MockAVSSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAVSSubscriber) EXPECT() *MockAVSSubscriberMockRecorder {
	return m.recorder
}

// SubscribeToNewPubkeyRegistrations mocks base method.
func (m *MockAVSSubscriber) SubscribeToNewPubkeyRegistrations() (chan *contractBLSApkRegistry.ContractBLSApkRegistryNewPubkeyRegistration, event.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToNewPubkeyRegistrations")
	ret0, _ := ret[0].(chan *contractBLSApkRegistry.ContractBLSApkRegistryNewPubkeyRegistration)
	ret1, _ := ret[1].(event.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubscribeToNewPubkeyRegistrations indicates an expected call of SubscribeToNewPubkeyRegistrations.
func (mr *MockAVSSubscriberMockRecorder) SubscribeToNewPubkeyRegistrations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToNewPubkeyRegistrations", reflect.TypeOf((*MockAVSSubscriber)(nil).SubscribeToNewPubkeyRegistrations))
}

// SubscribeToOperatorSocketUpdates mocks base method.
func (m *MockAVSSubscriber) SubscribeToOperatorSocketUpdates() (chan *contractRegistryCoordinator.ContractRegistryCoordinatorOperatorSocketUpdate, event.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToOperatorSocketUpdates")
	ret0, _ := ret[0].(chan *contractRegistryCoordinator.ContractRegistryCoordinatorOperatorSocketUpdate)
	ret1, _ := ret[1].(event.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubscribeToOperatorSocketUpdates indicates an expected call of SubscribeToOperatorSocketUpdates.
func (mr *MockAVSSubscriberMockRecorder) SubscribeToOperatorSocketUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToOperatorSocketUpdates", reflect.TypeOf((*MockAVSSubscriber)(nil).SubscribeToOperatorSocketUpdates))
}
