// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigensdk-go/services/avsregistry (interfaces: AvsRegistryService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bls "github.com/Layr-Labs/eigensdk-go/crypto/bls"
	types "github.com/Layr-Labs/eigensdk-go/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAvsRegistryService is a mock of AvsRegistryService interface.
type MockAvsRegistryService struct {
	ctrl     *gomock.Controller
	recorder *MockAvsRegistryServiceMockRecorder
}

// MockAvsRegistryServiceMockRecorder is the mock recorder for MockAvsRegistryService.
type MockAvsRegistryServiceMockRecorder struct {
	mock *MockAvsRegistryService
}

// NewMockAvsRegistryService creates a new mock instance.
func NewMockAvsRegistryService(ctrl *gomock.Controller) *MockAvsRegistryService {
	mock := &MockAvsRegistryService{ctrl: ctrl}
	mock.recorder = &MockAvsRegistryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvsRegistryService) EXPECT() *MockAvsRegistryServiceMockRecorder {
	return m.recorder
}

// GetOperatorPubkeys mocks base method.
func (m *MockAvsRegistryService) GetOperatorPubkeys(arg0 context.Context, arg1 [32]byte) (types.OperatorPubkeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorPubkeys", arg0, arg1)
	ret0, _ := ret[0].(types.OperatorPubkeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperatorPubkeys indicates an expected call of GetOperatorPubkeys.
func (mr *MockAvsRegistryServiceMockRecorder) GetOperatorPubkeys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorPubkeys", reflect.TypeOf((*MockAvsRegistryService)(nil).GetOperatorPubkeys), arg0, arg1)
}

// GetOperatorsAvsStateAtBlock mocks base method.
func (m *MockAvsRegistryService) GetOperatorsAvsStateAtBlock(arg0 context.Context, arg1 []byte, arg2 uint32) (map[[32]byte]types.OperatorAvsState, map[byte]*bls.G1Point, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorsAvsStateAtBlock", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[[32]byte]types.OperatorAvsState)
	ret1, _ := ret[1].(map[byte]*bls.G1Point)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOperatorsAvsStateAtBlock indicates an expected call of GetOperatorsAvsStateAtBlock.
func (mr *MockAvsRegistryServiceMockRecorder) GetOperatorsAvsStateAtBlock(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorsAvsStateAtBlock", reflect.TypeOf((*MockAvsRegistryService)(nil).GetOperatorsAvsStateAtBlock), arg0, arg1, arg2)
}
