// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigensdk-go/services/pubkeycompendium (interfaces: PubkeyCompendiumService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Layr-Labs/eigensdk-go/types"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPubkeyCompendiumService is a mock of PubkeyCompendiumService interface.
type MockPubkeyCompendiumService struct {
	ctrl     *gomock.Controller
	recorder *MockPubkeyCompendiumServiceMockRecorder
}

// MockPubkeyCompendiumServiceMockRecorder is the mock recorder for MockPubkeyCompendiumService.
type MockPubkeyCompendiumServiceMockRecorder struct {
	mock *MockPubkeyCompendiumService
}

// NewMockPubkeyCompendiumService creates a new mock instance.
func NewMockPubkeyCompendiumService(ctrl *gomock.Controller) *MockPubkeyCompendiumService {
	mock := &MockPubkeyCompendiumService{ctrl: ctrl}
	mock.recorder = &MockPubkeyCompendiumServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubkeyCompendiumService) EXPECT() *MockPubkeyCompendiumServiceMockRecorder {
	return m.recorder
}

// GetOperatorPubkeys mocks base method.
func (m *MockPubkeyCompendiumService) GetOperatorPubkeys(arg0 context.Context, arg1 common.Address) (types.OperatorPubkeys, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperatorPubkeys", arg0, arg1)
	ret0, _ := ret[0].(types.OperatorPubkeys)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetOperatorPubkeys indicates an expected call of GetOperatorPubkeys.
func (mr *MockPubkeyCompendiumServiceMockRecorder) GetOperatorPubkeys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperatorPubkeys", reflect.TypeOf((*MockPubkeyCompendiumService)(nil).GetOperatorPubkeys), arg0, arg1)
}
