name: check generated files (mocks+wire) up-to-date
on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  make-mocks:
    name: make generate (mocks+wire) and check for diffs
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install go1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: run make generate and check for diffs
        run: |
          make generate
          if [ ! -z "$(git status --porcelain)" ]; then
            printf "Current generated mocks not up to date\n"
            git diff
            git status
            exit 1
          fi
