name: unit-tests

on:
  push:
    branches:
      - dev
  pull_request:
  merge_group:

jobs:  
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Test
        run: make tests
